modLoader="javafml"
loaderVersion="[34,)"
license="GPL-3.0-only"
issueTrackerURL="https://github.com/Markil3/MinecraftPanorama/issues"
[[mods]]
modId="panorama"
version="${file.jarVersion}"
displayName="Panorama Mod"
updateJSONURL="https://raw.githubusercontent.com/Markil3/MinecraftPanorama/master/update-forge.json"
displayURL="https://markil3.github.io/MinecraftPanorama"
#logoFile="examplemod.png"
credits="Mojang Studios for the original screenshot code."
# A text field displayed in the mod UI
authors="Markil 3"
description='''
This Minecraft mod provides the ability to take panoramic screenshots at any time with the Screenshot key (default to F2 on most Minecraft installations). On top of that, these screenshots will occupy the main menu background, allowing you to relive your adventures every time you boot up the game.
'''
[[dependencies.panorama]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.panorama]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="CLIENT"
